### ISSUE TITLE
Accessing memory allocated in the stack outside the stack

### ISSUE THREAD

**Issue by hgourvest** [sahlberg/libsmb2#135]
I was testing how the library was reacting in case of connexion failure, and broken socket.
And it crash when trying to destroy context with events still waiting in the queues.
I have investigated and I found that event callback are called when desttroying context:

`pdu->cb(smb2, SMB2_STATUS_CANCELLED, NULL, pdu->cb_data); 
`
but "cb_data" whas allocated in the stack like in several functions like this:

```
int smb2_read(struct smb2_context *smb2, struct smb2fh *fh,
              uint8_t *buf, uint32_t count)
{
        struct sync_cb_data cb_data;

	cb_data.is_finished = 0;

	if (smb2_read_async(smb2, fh, buf, count,
                            generic_status_cb, &cb_data) != 0) {
		smb2_set_error(smb2, "smb2_read_async failed");
		return -1;
	}

	if (wait_for_reply(smb2, &cb_data) < 0) {
                return -1;
        }

	return cb_data.status;
}

```
when called outside the stack this function access protected memory and it crash:

```
static void generic_status_cb(struct smb2_context *smb2, int status,
                    void *command_data, void *private_data)
{
        struct sync_cb_data *cb_data = private_data;

        cb_data->is_finished = 1;
        cb_data->status = status;
}
```

I would suggest to avoid accesssing cb_data when status == SMB2_STATUS_CANCELLED

I love this library and hope you will take time to fix this issue.

best regards.

**Comment by hgourvest** [comment]
This is a patch that fix the issue in my project, but I realize all callbacks have to be checked too, I'm pretty sure it can crash in many other functions I don't use
[avoid_cb_crashing.txt](https://github.com/sahlberg/libsmb2/files/4177028/avoid_cb_crashing.txt)

.

**Comment by sahlberg** [comment]
Fixed in upstream now.
Please have a look, I refactored the code slightly to reduce the amount of indentation.

**Comment by hgourvest** [comment]
this issue is not fixed, there is at least all sync functions to fix.
