### ISSUE TITLE
Error in write/pwrite function

### ISSUE THREAD

**Issue by amosavian** [sahlberg/libsmb2#43]
Hi,

I'm developing a wrapper Swift framework for libsmb2. I successfully have run it on my **iOS** device but when I try write a file, after opening file with `O_WRONLY | O_CREAT | O_TRUNC` flag. Either using `smb2_write()` or `smb2_pwrite()` I get result `-1`. I also tried other flags combination for writing.

I've tried to use async version, thus I reimplemented `wait_for_reply` in Swift. It worked without issue for `smb2_rename_async()` (as I didn't find sync version).

In async version, `smb2_service()` returns negative value and `smb2_get_error()` prints `POLLHUP` error.

I reiterate this issue is only exist in writing functions and other functions work without any issue.

Thanks for this life saving library by the way. I also wrote building scripts and I can publish framework in Github after this issue got resolved.

**EDIT:** There is some minor issues in your code in apple platform which I will create a PR later to address them.

**EDIT 2:** An empty file is created in server every time I execute, if the file does not exist.

**Comment by amosavian** [comment]
This issue only exists when I connect to Western Digital MyCloud network hard drive. Other shares are okay 🤔😐

**Comment by amosavian** [comment]
This is My Cloud's `smb.conf` file. Maybe it helps to reproduce issue, I think `socket options` is the suspect.

```
[ global ]
netbios name = [redacted]
server string = [redacted]
veto files = /:2eDS_Store/.bin/Network Trash Folder/.systemfile/lost+found/Nas_Prog/mirrored/uploaded/.wdmc/.AppleDouble/
workgroup = WORKGROUP
security = user
passdb backend = smbpasswd
ldap ssl = no
local master = no
os level = 0
preferred master = no
smb2 leases = yes
fruit:copyfile= yes
printing = bsd
printcap name = /dev/null
disable spoolss = yes
max protocol = SMB3
max xmit = 131072
max log size = 10
log level = 0
socket options = IPTOS_LOWDELAY TCP_NODELAY SO_RCVBUF=2097152 SO_SNDBUF=2097152
delete veto files = yes
unix charset = UTF8
encrypt passwords = yes
map to guest = bad user
null passwords = yes
guest account = nobody
dns proxy = no
use mmap = yes
use spnego = yes
disable netbios = no
strict allocate = yes
csc policy = disable
min receivefile size = 16k
allocation roundup size = 0
create mask = 0777
directory mask  = 0777
force create mode = 0777
force directory mode = 0777
use sendfile = yes
smb passwd file = /etc/samba/smbpasswd
disable spoolss = yes
nt acl support = yes
acl map full control = yes
load printers = no
unix extensions = no
follow symlinks = yes
wide links = yes
printable = no
include = /etc/samba/tm_config.conf
```

**Comment by sahlberg** [comment]
fixed in 3353d70db9e6c11c0f51eb3880d89497ecd265b0

**Comment by amosavian** [comment]
I still get that `POLLHUP` message, **but this time for last chunk**. I decreased buffer size to 16200 bytes and the issue is gone.

**Comment by sahlberg** [comment]
Can you get me a wireshark trace when you get the pollhup?

**Comment by amosavian** [comment]
It is on my iOS device and unfortunately it's not jailbroken :(

I did some try and error. Buffer size 18000 was okay while 17999 and 18001 was not okay! Also 19600, 21000 are okay.

**Comment by sahlberg** [comment]
Please try current master.
It fixes an issue where the socket would stall and we would get SIGHUP due to a read/write that is too big to fit in the available credits count.

That should not have any effect on your i/o since it is all <64kb   but you never know.

**Comment by amosavian** [comment]
Unfortunately I’m on vacation and don’t have access to my NAS. 

My current implementation’s chunk size is 21kb.

**Comment by amosavian** [comment]
For now I’ve resolved this issue by writing file with adding null byte to end of file and make the size a multiplication of the chunk size I’ve begin writing file. Then truncate file to real size. For example if first written part of file is 1MiB and the last part is 700kb, I extend the last part to 1MiB by adding null bytes and then truncate the file to remove null bytes.

If you think this problem can not be addressed, you may close this issue and add proper documentation for other users.
